
import { Content, User, UserRole, AppNotification } from './types';

export const MOCK_USERS: User[] = [
  {
    id: '1',
    username: '@admin_jfl',
    displayName: 'Giga Admin',
    avatar: 'https://picsum.photos/seed/admin/200',
    role: UserRole.ADMIN,
    age: 30,
    nationality: 'Brasil',
    verified: true,
  },
  {
    id: '2',
    username: '@pixel_master',
    displayName: 'Pixel Master',
    avatar: 'https://picsum.photos/seed/creator/200',
    role: UserRole.CREATOR,
    age: 25,
    nationality: 'Portugal',
    verified: true,
    bio: 'Apaixonado por artes digitais e 3D.'
  },
  {
    id: '3',
    username: '@user_jfl',
    displayName: 'Usuário Comum',
    avatar: 'https://picsum.photos/seed/user/200',
    role: UserRole.USER,
    age: 20,
    nationality: 'Angola',
    verified: false,
  }
];

export const MOCK_CONTENT: Content[] = [
  {
    id: 'c1',
    title: 'Cinematic Drone 4K',
    description: 'Um vídeo incrível sobrevoando montanhas.',
    type: 'video',
    creatorId: '2',
    thumbnail: 'https://picsum.photos/seed/vid1/400/225',
    url: '#',
    views: 12500,
    likes: 840,
    downloads: 45,
    createdAt: '2023-10-01',
    tags: ['4k', 'drone', 'nature'],
    category: 'Natureza',
    ageRestricted: false,
  },
  {
    id: 'c2',
    title: 'Neon Cyberpunk Wallpaper',
    description: 'Ilustração digital em alta resolução.',
    type: 'image',
    creatorId: '2',
    thumbnail: 'https://picsum.photos/seed/img1/400/400',
    url: '#',
    views: 45000,
    likes: 3200,
    downloads: 12000,
    createdAt: '2023-11-15',
    tags: ['cyberpunk', 'wallpaper', 'art'],
    category: 'Arte Digital',
    ageRestricted: false,
  },
  {
    id: 'c3',
    title: 'Essential Toolkit v2.0',
    description: 'Conjunto de ferramentas para desenvolvedores.',
    type: 'file',
    creatorId: '1',
    thumbnail: 'https://picsum.photos/seed/file1/400/225',
    url: '#',
    views: 5600,
    likes: 120,
    downloads: 3400,
    createdAt: '2023-12-05',
    tags: ['tools', 'dev', 'zip'],
    category: 'Software',
    ageRestricted: false,
    version: '2.0.1',
    changelog: 'Fixing bugs and adding dark mode support.',
    requirements: 'Windows 10+, 8GB RAM',
  },
  {
    id: 'c4',
    title: 'Urban Exploration Series',
    description: 'Fotos proibidas de locais abandonados.',
    type: 'image',
    creatorId: '2',
    thumbnail: 'https://picsum.photos/seed/urb/400/300',
    url: '#',
    views: 8900,
    likes: 450,
    downloads: 89,
    createdAt: '2024-01-20',
    tags: ['urban', 'abandoned'],
    category: 'Fotografia',
    ageRestricted: true,
  }
];

export const MOCK_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'n1',
    userId: '2',
    type: 'like',
    title: 'Novo Like!',
    message: '@user_jfl curtiu seu vídeo "Cinematic Drone 4K".',
    contentId: 'c1',
    createdAt: new Date().toISOString(),
    read: false,
  },
  {
    id: 'n2',
    userId: '2',
    type: 'comment',
    title: 'Novo Comentário',
    message: '@user_jfl comentou em "Neon Cyberpunk Wallpaper".',
    contentId: 'c2',
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    read: false,
  },
  {
    id: 'n3',
    userId: '2',
    type: 'moderation',
    title: 'Conteúdo Sinalizado',
    message: 'Seu arquivo "Toolkit v2.0" foi sinalizado para revisão manual.',
    contentId: 'c3',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    read: false,
  }
];
